### PR TITLE
Fixes for layout management

### PR DESCRIPTION
**Pull request by humdingerb**
* Use layout aware constructors and remove now unneeded
  BRect pixel computing
* Put target drop view in a scroll view, so it's similar to
  the source drag view
* Remove getCenterRect(), as there's CenterOnScreen() in BWindow
* Use B_TITLED_WINDOW instead of B_DOCUMENT_WINDOW to not have
  the big resize which would be drawn over the arrow widget of the vertical
  scrollbar
* Use SetSizeLimit to have a minimal window size
* Make default main window size a bit smaller
* Add 'N' as shortcut for a new window
* Use sentence casing
* Update Readme screenshot

### CODE REVIEW

**Comment by humdingerb** [comment]
I'm by far no expert on layout management, but had my share of dealing with it with past projects. I'm still not totally clear on the why of every change, but I learned those things with trial&error and by looking at the code of various projects... :)

The "Drop parameter" window isn't quite perfect, as it resizes not that great, but it's a start...

**Comment by dewf** [comment]
Thank you very much for these changes! I appreciate the help.

Also, this was my first pull request (on any project) - exciting times! 🥳

**Comment by humdingerb** [comment]
Thanks and concrats, then. :)

BTW, I can't seem to make the dnd work between two windows as it's seem in the screenshot for the readme. I may be doing something wrong...
The "Drop properties" window does pop up, but it also freezes the main window. In Terminal it says: "drop dialog - ShowAndWait received spurious msg" over and over. BTW, in order not to peg a core here, it'd be prudent to insert a `snooze(100000)` in the while-loop at https://github.com/dewf/dnd-inspect/blob/master/DropDialog.cpp#L147

**Comment by dewf** [comment]
Hmm, very interesting.!

My reason for using `while (receive_data(...))` was dumb (more on that in a second), but it's my understanding that `receive_data` blocks until there's a message available. I put it in the loop because I didn't know whether threads receive any other kinds of messages, other than the specific one I was waiting for. I guess your experience answers my question - clearly they do, sometimes!

It works fine on my system (hrev52295 / hybrid 32-bit) - no spurious thread messages, so it's blocking/waiting for the drop to complete. Which version of Haiku are you using? 32- or 64-bit? I'll have to install that version in a VM to test the behavior.

As for why I was blocking in the first place - I was having an issue with receiving the final drop message, which was happening because I didn't understand `SendReply()` has a parameter indicating where replies are supposed to be sent to. But I mistakenly thought maybe it was because the message had to be responded to before MessageReceived() exited, hence the blocking.

So the short version is I will get rid of that and make it a normal modal dialog with no thread blocking. (In fact it might not even need to be modal at all, but I'd have to look). I'll try to take care of that tonight.

But in the meantime, do let me know what your Haiku version / arch is. Even if the blocking thing is unnecessary here, I would like to know why it's broken, because I definitely have to use it in another project I'm working on.

**Comment by humdingerb** [comment]
I'm on a recent nightly 32bit, around hrev52301, I think. i7, 8 cores (HT) running natively.

**Comment by dewf** [comment]
I tried it with 52309/32-bit (which displays as 53013 in the 'About' dialog? huh?), and I'm now getting the same problem you're having. I'll try it again later today with the latest nightly, and then go from there. Thank you for bringing this to my attention!

**Comment by dewf** [comment]
Should be fixed now! d21f116985e7e8a59384f78937227c607c5fd0ea

Explanation: https://discuss.haiku-os.org/t/what-changed-with-receive-data/8441/3

**Comment by humdingerb** [comment]
Confirmed!

> I tried it with 52309/32-bit (which displays as 53013 in the 'About' dialog? huh?)

Strange (I assume you meant you tried hrev53009/32-bit). Maybe you installed hrev53009 and then shortly after updated with pkgman or SoftwareUpdater...

**Pull request merged**
